name: CI

on: [push]

env:
  CI: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    uses: inrupt/typescript-sdk-tools/.github/workflows/reusable-lint.yml@v3
    with:
      build: true

  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # We test against different OSes, because the build toolchain has OS-specific dependencies.
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        node-version: ["22.x", "20.x"]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run test
      # Upload coverage for sonarcube (only matching OS and one node version required)
      - uses: actions/upload-artifact@v5
        if: ${{ matrix.node-version == '22.x' }}
        with:
          name: code-coverage-${{ matrix.os }}-${{matrix.node-version}}
          path: coverage/

  sonar-scan:
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: [unit-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # Sonar analysis needs the full history for features like automatic assignment of bugs. If the following step
          # is not included the project will show a warning about incomplete information.
          fetch-depth: 0
      - uses: actions/download-artifact@v6
        with:
          name: code-coverage-ubuntu-latest-22.x
          path: coverage/
      - uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
