name: CI

on: [push]

env:
  CI: true
jobs:
  audit-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: npm audit --audit-level=moderate
      - run: npm ci
      - run: npm run check-licenses
      - run: npx package-check
      - run: npm run lint

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 14.x, 12.x]
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm test
