name: End-to-end Tests (Node)

on:
  push:
  # Allow manual triggering, e.g. to run end-to-end tests against Dependabot PRs:
  workflow_dispatch:

env:
  CI: true
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  e2e-node:
    runs-on: ${{ matrix.os }}
    environment:
      name: ${{ matrix.environment-name }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: ["22.x", "20.x"]
        environment-name: ["ESS PodSpaces", "ESS Release-2-3", "ESS Next"]
        experimental: [false]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - run: npm run test:e2e:node
        env:
          E2E_TEST_IDP: ${{ secrets.E2E_TEST_IDP }}
          E2E_TEST_ENVIRONMENT: ${{ matrix.environment-name }}
          E2E_TEST_OWNER_CLIENT_ID: ${{ secrets.E2E_TEST_OWNER_CLIENT_ID }}
          E2E_TEST_OWNER_CLIENT_SECRET: ${{ secrets.E2E_TEST_OWNER_CLIENT_SECRET }}
